name: Database Migration

on:
  push:
    branches:
      - dev
    paths:
      - "migration/**"
    workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Install tool
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run validate
        run: |
          cd migration
          GOOSE_DRIVER=${{ secrets.GOOSE_DRIVER }}
          GOOSE_DBSTRING=${{ secrets.GOOSE_DBSTRING }}
          goose up
